#!/bin/bash

# Quick commands to fix the ECONNREFUSED error and run your app

echo "🔧 Expense Tracker - Docker Quick Start"
echo ""
echo "✅ PRODUCTION MODE IS NOW WORKING!"
echo "   Access UI at: http://localhost"
echo ""
echo "Choose your mode:"
echo ""
echo "1️⃣  DEVELOPMENT MODE (with hot reload)"
echo "   - Frontend: http://localhost:5173"
echo "   - Backend:  http://localhost:8080"
echo ""
echo "   Commands:"
echo "   docker-compose -f docker-compose.dev.yml down"
echo "   docker-compose -f docker-compose.dev.yml up -d --build"
echo ""
echo "2️⃣  PRODUCTION MODE (with nginx)"
echo "   - Frontend: http://localhost:80"
echo "   - Backend:  http://localhost:8080"
echo ""
echo "   Commands:"
echo "   docker-compose down"
echo "   docker-compose up -d --build"
echo ""
echo "📝 View Logs:"
echo "   docker-compose logs -f"
echo "   docker-compose logs -f frontend"
echo "   docker-compose logs -f backend"
echo ""
echo "🛑 Stop Everything:"
echo "   docker-compose down"
echo "   docker-compose -f docker-compose.dev.yml down"
echo ""
